onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - esbuild
  - msgpackr-extract

# Dependency catalogs for better organization and version management
catalogs:
  # Effect-TS ecosystem packages - runtime dependencies
  effect:
    "@effect/experimental": ^0.48.7
    "@effect/language-service": ^0.19.0
    "@effect/opentelemetry": ^0.50.6
    "@effect/platform": ^0.84.6
    "@effect/platform-bun": ^0.69.4
    "@typed/id": ^0.17.2
    "effect": ^3.16.3
  
  # AI and ML packages
  ai:
    "@ai-sdk/assemblyai": 1.0.1
    "@ai-sdk/deepgram": 1.0.1
    "@ai-sdk/elevenlabs": 1.0.1
    "@ai-sdk/gladia": 1.0.1
    "@ai-sdk/groq": 2.0.4
    "@ai-sdk/openai": 2.0.7
    "ai": 5.0.8
  
  # Core packages
  core:
    "@restatedev/restate-sdk": ^1.8.1
    "@restatedev/restate-sdk-clients": ^1.8.1

  # Testing framework and utilities
  test:
    "@effect/vitest": ^0.23.3
    "@vitest/ui": ^3.2.2
    "vitest": ^3.2.2

  # Linting and formatting tools
  lint:
    "ultracite": 4.2.8
    "@biomejs/biome": 1.9.4

  # Types and TypeScript compiler
  types:
    "typescript": ^5.8.3
    "ts-patch": ^3.3.0
    "@types/bun": ^1.2.20
