onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - esbuild
  - msgpackr-extract

# Dependency catalogs for better organization and version management
catalogs:
  # Effect-TS ecosystem packages - runtime dependencies
  effect:
    "@effect/cli": ^0.69.0
    "@effect/experimental": ^0.54.5
    "@effect/language-service": ^0.35.2
    "@effect/opentelemetry": ^0.56.1
    "@effect/platform": ^0.90.2
    "@effect/platform-bun": ^0.78.0
    "@typed/id": ^0.17.2
    "effect": ^3.17.7

  # AI and ML packages
  ai:
    "@ai-sdk/assemblyai": 1.0.1
    "@ai-sdk/deepgram": 1.0.1
    "@ai-sdk/elevenlabs": 1.0.1
    "@ai-sdk/gladia": 1.0.1
    "@ai-sdk/groq": 2.0.5
    "@ai-sdk/openai": 2.0.10
    "ai": 5.0.10

  # Core packages
  core:
    "@restatedev/restate-sdk": ^1.8.1
    "@restatedev/restate-sdk-clients": ^1.8.1

  # Testing framework and utilities
  test:
    "@effect/vitest": ^0.25.0
    "@vitest/ui": ^3.2.4
    "vitest": ^3.2.4

  # Linting and formatting tools
  lint:
    "ultracite": 5.1.2
    "@biomejs/biome": 2.2.0

  # Types and TypeScript compiler
  types:
    "typescript": ^5.9.2
    "ts-patch": ^3.3.0
    "@types/bun": ^1.2.20

  # Less used dependencies
  other:
    "yaml": 2.8.1
